info:
  contact: {}
paths:
  /index:
    get:
      responses: {}
      tags:
      - 首页
  /user/createUser:
    post:
      parameters:
      - description: 用户名
        in: query
        name: name
        type: string
      - description: 密码
        in: query
        name: passwd
        type: string
      - description: 确认密码
        in: query
        name: repasswd
        type: string
      responses: {}
      summary: 新增用户
      tags:
      - 用户模块
  /user/deleteUser:
    delete:
      parameters:
      - description: id
        in: query
        name: id
        type: string
      responses: {}
      summary: 删除用户
      tags:
      - 用户模块
  /user/getUserList:
    get:
      responses: {}
      summary: 用户列表
      tags:
      - 用户模块
  /user/login:
    post:
      parameters:
      - description: name
        in: query
        name: name
        type: string
      - description: passwd
        in: query
        name: passwd
        type: string
      responses: {}
      summary: 用户登录
      tags:
      - 用户模块
  /user/updateUser:
    put:
      parameters:
      - description: id
        in: query
        name: id
        type: string
      - description: name
        in: query
        name: name
        type: string
      - description: passwd
        in: query
        name: passwd
        type: string
      - description: phone
        in: query
        name: phone
        type: string
      - description: email
        in: query
        name: email
        type: string
      responses: {}
      summary: 修改用户
      tags:
      - 用户模块
swagger: "2.0"
